org.gradle.jvmargs=-Xmx2G
modName=MoogsVoyagerStructures
minecraftVersion=1.21
modVersion=5.0.6
modId=mvs
modDescription=160+ structures made with vanilla blocks and entities bringing life to your world! Discover loot, enemies, & villagers along the way!
modHomepage=https://www.curseforge.com/minecraft/mc-mods/moogs-voyager-structures
modSources=https://github.com/Moog-s-Mods/MoogsVoyagerStructures
modReleases=https://github.com/Moog-s-Mods/MoogsVoyagerStructures/releases
modIssues=https://github.com/Moog-s-Mods/MoogsVoyagerStructures/issues
modDiscord=https://discord.gg/S5nffJbuvA
modKofi=https://ko-fi.com/finndog
modCurseforge=https://www.curseforge.com/minecraft/mc-mods/moogs-voyager-structures
modModrinth=https://modrinth.com/mod/moogs-voyager-structures

# Publishing display customization
publishDisplayPrefix=MVS
publishDisplaySuffix=[UNIVERSAL]

# Publishing platform settings
modrinthProjectId=OQAgZMH1
curseforgeProjectId=656977
curseforgeProjectSlug=moogs-voyager-structures
publishMcStart=1.21
publishMcEnd=1.21.11

# Discord webhook settings
discordAvatarUrl=https://media.forgecdn.net/avatars/thumbnails/869/885/64/64/638285724433169131.png
discordEmbedColor=#9033af