org.gradle.jvmargs=-Xmx2G
modName=MoogsVoyagerStructures
minecraftVersion=1.21
modVersion=5.0.1
modId=mvs

# Publishing display customization
publishDisplayPrefix=MVS
publishDisplaySuffix=[UNIVERSAL]

# Publishing platform settings
modrinthProjectId=OQAgZMH1
curseforgeProjectId=656977
publishMcStart=1.21
publishMcEnd=1.21.10