org.gradle.jvmargs=-Xmx2G
modName=MoogsVoyagerStructures
minecraftVersion=1.20
modVersion=5.0.2
modId=mvs

# Publishing display customization
publishDisplayPrefix=MVS
publishDisplaySuffix=[UNIVERSAL]

# Publishing platform settings
modrinthProjectId=OQAgZMH1
curseforgeProjectId=656977
publishMcStart=1.20
publishMcEnd=1.20.6